#### **Análise Exploratória**

In [1]:
#realizando importação da biblioteca principal
import pandas as pd

In [2]:
#trazendo o arquivo

excel = "base_vendas_tecnologia_pipeline.xlsx"
dados = pd.read_excel(excel)

In [3]:
#trazendo o nosso DataFrame
dados.head()

,id_venda,nome_produto,categoria,quantidade,preco_unitario,faturamento_total,vendedor,data_venda
0,1,NaN,Áudio,4,1289.33,5157.32,Mariana,2025-01-14
1,2,NaN,Hardware,1,905.17,905.17,Carlos,2025-01-30
2,3,Webcam Logitech,Periférico,12,5566.03,66792.36,Mariana,2025-03-11
3,4,Placa de Vídeo RTX 4060,Impressora,13,7404.74,96261.62,João,2025-04-08
4,5,Teclado Mecânico,Armazenamento,3,1924.33,5772.99,João,2025-04-08

In [4]:
#verificando a quantidade de linhas e colunas 

dados.shape

(100, 8)

In [5]:
#verificando o tipo de dados 

dados.dtypes
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_venda           100 non-null    int64
 1   nome_produto       84 non-null     object
 2   categoria          100 non-null    object
 3   quantidade         100 non-null    int64
 4   preco_unitario     100 non-null    float64
 5   faturamento_total  100 non-null    float64
 6   vendedor           100 non-null    object
 7   data_venda         100 non-null    object
dtypes: float64(2), int64(2), object(4)
memory usage: 6.4+ KB

In [6]:
#Regra para o nosso DataFrame -- retirar valores nulos do nosso dataFrame

#verificando se há dados nulos

dados.isnull().sum()

id_venda              0
nome_produto         16
categoria             0
quantidade            0
preco_unitario        0
faturamento_total     0
vendedor              0
data_venda            0
dtype: int64

In [7]:
#retirando valores nulos 
dados = dados.dropna(subset="nome_produto")

In [8]:
#verificando se foi retirado os valores nulos
dados.isna().sum()

id_venda             0
nome_produto         0
categoria            0
quantidade           0
preco_unitario       0
faturamento_total    0
vendedor             0
data_venda           0
dtype: int64

In [9]:
#verificando os dados 
dados.dtypes

id_venda               int64
nome_produto          object
categoria             object
quantidade             int64
preco_unitario       float64
faturamento_total    float64
vendedor              object
data_venda            object
dtype: object

In [10]:
dados.head()

,id_venda,nome_produto,categoria,quantidade,preco_unitario,faturamento_total,vendedor,data_venda
2,3,Webcam Logitech,Periférico,12,5566.03,66792.36,Mariana,2025-03-11
3,4,Placa de Vídeo RTX 4060,Impressora,13,7404.74,96261.62,João,2025-04-08
4,5,Teclado Mecânico,Armazenamento,3,1924.33,5772.99,João,2025-04-08
6,7,Headset HyperX,Móveis,2,8274.71,16549.42,Lucas,2025-02-18
7,8,Mouse Gamer,Impressora,10,1731.38,17313.80,João,2025-01-09

In [11]:
#realizando a alteração do tipo na coluna data
dados["data_venda"] = pd.to_datetime(dados["data_venda"],errors="coerce")
print(dados["data_venda"])

2    2025-03-11
3    2025-04-08
4    2025-04-08
6    2025-02-18
7    2025-01-09
        ...
95   2025-02-11
96   2025-02-23
97   2025-02-14
98   2025-01-03
99   2025-01-28
Name: data_venda, Length: 84, dtype: datetime64[ns]

In [12]:
#verificando se foi ajustado 
dados.dtypes

id_venda                      int64
nome_produto                 object
categoria                    object
quantidade                    int64
preco_unitario              float64
faturamento_total           float64
vendedor                     object
data_venda           datetime64[ns]
dtype: object

In [13]:
#padronizando as informações das colunas
dados["id_venda"] =  dados["id_venda"].astype(str)
print(dados["id_venda"].dtype)

object

In [14]:
dados["nome_produto"] = dados["nome_produto"].str.strip().str.capitalize()
dados["categoria"] = dados["categoria"].str.strip().str.capitalize()
dados["vendedor"] = dados["vendedor"].str.strip().str.title()

In [15]:
#visualizando o nosso DataFrame
dados.head()

,id_venda,nome_produto,categoria,quantidade,preco_unitario,faturamento_total,vendedor,data_venda
2,3,Webcam logitech,Periférico,12,5566.03,66792.36,Mariana,2025-03-11
3,4,Placa de vídeo rtx 4060,Impressora,13,7404.74,96261.62,João,2025-04-08
4,5,Teclado mecânico,Armazenamento,3,1924.33,5772.99,João,2025-04-08
6,7,Headset hyperx,Móveis,2,8274.71,16549.42,Lucas,2025-02-18
7,8,Mouse gamer,Impressora,10,1731.38,17313.80,João,2025-01-09

In [16]:
dados.to_excel("dados_tratados_exploração.xlsx",index=False)

In [17]:
dados.head()

,id_venda,nome_produto,categoria,quantidade,preco_unitario,faturamento_total,vendedor,data_venda
2,3,Webcam logitech,Periférico,12,5566.03,66792.36,Mariana,2025-03-11
3,4,Placa de vídeo rtx 4060,Impressora,13,7404.74,96261.62,João,2025-04-08
4,5,Teclado mecânico,Armazenamento,3,1924.33,5772.99,João,2025-04-08
6,7,Headset hyperx,Móveis,2,8274.71,16549.42,Lucas,2025-02-18
7,8,Mouse gamer,Impressora,10,1731.38,17313.80,João,2025-01-09